<Project Sdk="Microsoft.NET.Sdk">
  <!-- This whole thing is just a setting mess explaning to the compiler to make it buildable in both linux and windows -->
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>

    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <!-- Imported Libraries -->
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="Svg.Skia" Version="3.4.0" />

    <!-- Copy Assets folder to output folder otherwise no icons -->
    <None Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
