<Project Sdk="Microsoft.NET.Sdk">
  <!-- This whole thing is just a setting mess explaning to the compiler to make it buildable in both linux and windows -->
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <ApplicationIcon>Assets\App.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <NoWarn>$(NoWarn);NU1701</NoWarn>

    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

    <!-- Shiping settings -->
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <AssemblyTitle>TrackFlow</AssemblyTitle>
    <Product>TrackFlow</Product>
    <Description>A minimal app for tracking, planning and scheduling your expenses and business</Description>

    <Company>Nahom Ziyin</Company>
    <Authors>Nahom Ziyin</Authors>
    <Copyright>
      © 2026 Nahom Ziyin. All rights reserved.
    </Copyright>

    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Imported Libraries -->
    <PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="Svg.Skia" Version="3.4.0" />

    <!-- Copy Assets folder to output folder otherwise no icons -->
    <None Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
